"""《史记·留侯世家》张良事件种子数据。"""

from __future__ import annotations

from typing import Any

from ..store import EventStore

SOURCE_URL = "https://wikisource.org/wiki/%E7%95%99%E5%80%99%E4%B8%96%E5%AE%B6"
SEED_MARKER = "MapStory seed: zhang-liang-liuhou"


def _remark(summary: str) -> str:
    return f"{summary} 来源：司马迁《史记·留侯世家》（Wikisource）。{SEED_MARKER}"


ZHANG_LIANG_LIUHOU_EVENTS: list[dict[str, Any]] = [
    {
        "time": "-249",
        "time_note": "韩悼惠王二十三年，约前250；项目负年份按现有结构化时间存储。",
        "lat": 34.40,
        "lon": 113.74,
        "location_note": "韩国新郑（今河南新郑）",
        "persons": "张平, 张良",
        "event": "张良之父张平卒；张良尚少，未仕韩。",
        "priority": "fact",
        "remark": _remark("原文以张良祖、父五世相韩起笔，并记张平卒后二十年秦灭韩。"),
    },
    {
        "time": "-229",
        "time_note": "前230；韩破后。",
        "lat": 34.40,
        "lon": 113.74,
        "location_note": "韩国新郑（今河南新郑）",
        "persons": "张良",
        "event": "秦灭韩后，张良散家财求客刺秦，为韩报仇。",
        "priority": "fact",
        "remark": _remark("原文记“韩破”后张良不葬弟，尽家财求刺客。"),
    },
    {
        "time": "-228",
        "time_note": "秦末前期，具体年不详。",
        "lat": 33.73,
        "lon": 114.88,
        "location_note": "淮阳（今河南周口淮阳）",
        "persons": "张良",
        "event": "张良曾在淮阳学礼。",
        "priority": "fact",
        "remark": _remark("原文记“良尝学礼淮阳”。"),
    },
    {
        "time": "-218",
        "time_note": "秦始皇东游前后；仓海君地望不详。",
        "lat": 35.10,
        "lon": 119.30,
        "location_note": "东海一带（仓海君地望不详）",
        "persons": "张良, 仓海君",
        "event": "张良东见仓海君，得力士并制铁椎。",
        "priority": "doubt",
        "remark": _remark("原文只称“东见仓海君”，此处坐标仅作东海方向的地图锚点。"),
    },
    {
        "time": "-218",
        "time_note": "秦始皇二十九年，前218。",
        "lat": 35.06,
        "lon": 113.94,
        "location_note": "博浪沙（今河南原阳一带）",
        "persons": "张良, 秦始皇",
        "event": "张良与力士在博浪沙狙击秦始皇，误中副车。",
        "priority": "fact",
        "remark": _remark("原文记秦皇帝东游，张良与客狙击于博浪沙，误中副车。"),
    },
    {
        "time": "-218",
        "time_note": "博浪沙事后。",
        "lat": 34.31,
        "lon": 117.95,
        "location_note": "下邳（今江苏邳州一带）",
        "persons": "张良",
        "event": "秦大索天下，张良更名姓，亡匿下邳。",
        "priority": "fact",
        "remark": _remark("原文记秦皇帝大怒，大索天下，张良亡匿下邳。"),
    },
    {
        "time": "-217",
        "time_note": "下邳匿居期间，具体年不详。",
        "lat": 34.31,
        "lon": 117.95,
        "location_note": "下邳圯桥（今江苏邳州一带）",
        "persons": "张良, 黄石公",
        "event": "张良在下邳圯桥遇老父，受书后习读。",
        "priority": "fact",
        "remark": _remark("原文详记圯上取履、五日复会，老父授书。"),
    },
    {
        "time": "-209",
        "time_note": "陈涉起兵后十年之期，前209。",
        "lat": 34.31,
        "lon": 117.95,
        "location_note": "下邳（今江苏邳州一带）",
        "persons": "张良, 刘邦",
        "event": "陈涉等起兵，张良聚少年百余人；道遇沛公，遂属刘邦。",
        "priority": "fact",
        "remark": _remark("原文记张良欲从景驹，道遇沛公；沛公略地下邳，张良归属。"),
    },
    {
        "time": "-208",
        "time_note": "秦二世二年左右。",
        "lat": 35.08,
        "lon": 117.15,
        "location_note": "薛（今山东滕州、薛城一带）",
        "persons": "张良, 刘邦, 项梁, 韩成",
        "event": "张良随沛公至薛见项梁，建议立韩成为韩王。",
        "priority": "fact",
        "remark": _remark("原文记沛公之薛见项梁，张良说项梁立韩成以益树党。"),
    },
    {
        "time": "-208",
        "time_note": "韩成既立后。",
        "lat": 34.16,
        "lon": 113.48,
        "location_note": "阳翟、颍川（今河南禹州一带）",
        "persons": "张良, 韩成",
        "event": "张良为韩申徒，与韩王将千余人西略韩地，往来颍川为游兵。",
        "priority": "fact",
        "remark": _remark("原文记张良与韩王略韩地，秦复取，往来为游兵颍川。"),
    },
    {
        "time": "-207",
        "time_note": "入关前。",
        "lat": 34.62,
        "lon": 112.45,
        "location_note": "雒阳、轘辕（今河南洛阳至登封一带）",
        "persons": "张良, 刘邦",
        "event": "刘邦从雒阳南出轘辕，张良引兵从之，攻下韩地十余城。",
        "priority": "fact",
        "remark": _remark("原文记沛公之从雒阳，南出轘辕，张良引兵从沛公。"),
    },
    {
        "time": "-207",
        "time_note": "入武关前。",
        "lat": 32.99,
        "lon": 112.53,
        "location_note": "宛（今河南南阳）",
        "persons": "张良, 刘邦",
        "event": "张良随刘邦南攻宛，西入武关。",
        "priority": "fact",
        "remark": _remark("原文记与良俱南，攻下宛，西入武关。"),
    },
    {
        "time": "-207",
        "time_note": "秦亡前夕。",
        "lat": 34.16,
        "lon": 109.32,
        "location_note": "峣关、蓝田（今陕西蓝田一带）",
        "persons": "张良, 刘邦, 郦食其",
        "event": "张良献疑兵、利诱与乘懈击秦之策，刘邦大破秦军至蓝田。",
        "priority": "fact",
        "remark": _remark("原文记张良劝先疑兵啗秦将，又劝趁其懈怠击之。"),
    },
    {
        "time": "-207",
        "time_note": "秦王子婴降后。",
        "lat": 34.34,
        "lon": 108.71,
        "location_note": "咸阳、霸上（今陕西西安、咸阳一带）",
        "persons": "张良, 刘邦, 樊哙",
        "event": "刘邦入秦宫欲留居，张良劝听樊哙言，还军霸上。",
        "priority": "fact",
        "remark": _remark("原文记张良以“助桀为虐”等语劝刘邦出秦宫。"),
    },
    {
        "time": "-206",
        "time_note": "汉元年前后，鸿门宴。",
        "lat": 34.38,
        "lon": 109.21,
        "location_note": "鸿门（今陕西临潼一带）",
        "persons": "张良, 刘邦, 项羽, 项伯, 樊哙",
        "event": "鸿门危局中，张良转告项伯夜报，促成刘邦解释并留谢项羽。",
        "priority": "fact",
        "remark": _remark("原文记项伯夜驰入军私见张良，张良告刘邦，并在鸿门留谢。"),
    },
    {
        "time": "-206",
        "time_note": "汉元年，刘邦之国汉中。",
        "lat": 33.15,
        "lon": 106.68,
        "location_note": "褒中、汉中（今陕西汉中一带）",
        "persons": "张良, 刘邦, 项伯",
        "event": "刘邦入汉中，张良送至褒中，建议烧绝栈道以安项羽之心。",
        "priority": "fact",
        "remark": _remark("原文记汉王赐张良金珠，张良献项伯请汉中地，并劝烧栈道。"),
    },
    {
        "time": "-205",
        "time_note": "彭城败后。",
        "lat": 34.45,
        "lon": 116.33,
        "location_note": "下邑（今安徽砀山、河南永城一带）",
        "persons": "张良, 刘邦, 黥布, 彭越, 韩信",
        "event": "汉败至下邑，张良建议联络黥布、彭越并任韩信一面。",
        "priority": "fact",
        "remark": _remark("原文记汉王至下邑问计，张良提出可共功者三人。"),
    },
    {
        "time": "-203",
        "time_note": "汉三年。",
        "lat": 34.79,
        "lon": 113.38,
        "location_note": "荥阳（今河南荥阳）",
        "persons": "张良, 刘邦, 郦食其",
        "event": "楚围荥阳时，张良以“借箸筹之”驳回复立六国后裔之议。",
        "priority": "fact",
        "remark": _remark("原文记汉王方食，张良从外来谒，论八不可，令销印。"),
    },
    {
        "time": "-203",
        "time_note": "汉四年，韩信破齐后。",
        "lat": 36.82,
        "lon": 118.31,
        "location_note": "齐地临淄（今山东淄博一带）",
        "persons": "张良, 刘邦, 韩信",
        "event": "韩信欲自立齐王，张良劝刘邦因势立之，并授齐王印信。",
        "priority": "fact",
        "remark": _remark("原文记汉四年韩信破齐欲自立，张良说汉王使良授印信。"),
    },
    {
        "time": "-202",
        "time_note": "汉五年冬。",
        "lat": 34.06,
        "lon": 114.84,
        "location_note": "固陵、阳夏南（今河南太康一带）",
        "persons": "张良, 刘邦, 韩信, 彭越",
        "event": "刘邦壁固陵，诸侯不至；张良建议分地给韩信、彭越，诸侯遂至。",
        "priority": "fact",
        "remark": _remark("原文记五年冬追楚至阳夏南不利，张良说汉王，用计诸侯皆至。"),
    },
    {
        "time": "-201",
        "time_note": "汉六年正月。",
        "lat": 34.73,
        "lon": 116.93,
        "location_note": "留（今江苏沛县一带）",
        "persons": "张良, 刘邦, 萧何",
        "event": "刘邦封功臣，张良辞齐三万户，请封始从高祖之地“留”，遂为留侯。",
        "priority": "fact",
        "remark": _remark("原文记高帝称其运筹功，张良愿封留足矣。"),
    },
    {
        "time": "-201",
        "time_note": "汉六年，封功臣未定时。",
        "lat": 34.62,
        "lon": 112.45,
        "location_note": "雒阳南宫（今河南洛阳）",
        "persons": "张良, 刘邦, 雍齿",
        "event": "刘邦忧诸将议功不决，张良建议先封雍齿以安群臣。",
        "priority": "fact",
        "remark": _remark("原文记上在雒阳南宫见诸将偶语，张良以先封雍齿解之。"),
    },
    {
        "time": "-201",
        "time_note": "汉初定都议。",
        "lat": 34.27,
        "lon": 108.94,
        "location_note": "关中、长安（今陕西西安）",
        "persons": "张良, 刘邦, 刘敬",
        "event": "张良赞同刘敬都关中之议，刘邦西都关中，张良从入关。",
        "priority": "fact",
        "remark": _remark("原文记张良比较雒阳与关中形势，称关中为金城千里、天府之国。"),
    },
    {
        "time": "-199",
        "time_note": "高帝欲易太子前后，具体年不详。",
        "lat": 34.27,
        "lon": 108.94,
        "location_note": "长安（今陕西西安）",
        "persons": "张良, 吕后, 吕泽, 刘盈, 商山四皓",
        "event": "吕后求计保太子，张良建议厚礼迎商山四皓，使太子羽翼渐成。",
        "priority": "fact",
        "remark": _remark("原文记吕泽劫留侯问计，张良以四人为太子助。"),
    },
    {
        "time": "-196",
        "time_note": "汉十一年，黥布反。",
        "lat": 34.31,
        "lon": 108.99,
        "location_note": "曲邮、灞上附近（今陕西西安一带）",
        "persons": "张良, 刘邦, 刘盈",
        "event": "刘邦东击黥布，张良病中强起至曲邮，劝勿与楚人争锋并令太子监关中兵。",
        "priority": "doubt",
        "remark": _remark("原文记留侯病，自强起至曲邮见上；曲邮地望据注为长安邮亭，坐标为近似。"),
    },
    {
        "time": "-195",
        "time_note": "汉十二年，燕置酒。",
        "lat": 34.27,
        "lon": 108.94,
        "location_note": "长安宫廷（今陕西西安）",
        "persons": "张良, 刘邦, 刘盈, 商山四皓, 戚夫人",
        "event": "商山四皓随太子侍宴，高帝见太子羽翼已成，终不易太子。",
        "priority": "fact",
        "remark": _remark("原文记四人从太子入宴，高帝目送后谓戚夫人难动。"),
    },
    {
        "time": "-195",
        "time_note": "高帝晚年，从击代事，具体年不详。",
        "lat": 39.33,
        "lon": 112.43,
        "location_note": "马邑（今山西朔州一带）",
        "persons": "张良, 刘邦",
        "event": "张良从刘邦击代，出奇计于马邑下。",
        "priority": "fact",
        "remark": _remark("原文概述留侯从上击代，出奇计下马邑。"),
    },
    {
        "time": "-195",
        "time_note": "高帝崩后。",
        "lat": 34.27,
        "lon": 108.94,
        "location_note": "长安（今陕西西安）",
        "persons": "张良, 吕后",
        "event": "张良自称愿弃人间事从赤松子游，学辟谷导引；高帝崩后，吕后劝其进食。",
        "priority": "fact",
        "remark": _remark("原文记留侯愿从赤松子游，吕后德留侯而强食之。"),
    },
    {
        "time": "-187",
        "time_note": "高帝崩后八年。",
        "lat": 34.73,
        "lon": 116.93,
        "location_note": "留地、黄石冢相关祭祀地（今江苏沛县一带）",
        "persons": "张良, 张不疑",
        "event": "张良卒，谥文成侯；其后与黄石信仰一并祭祀。",
        "priority": "doubt",
        "remark": _remark("原文记后八年卒，并记留侯死后并葬黄石冢；此坐标以留地作地图锚点。"),
    },
]


def seed_zhang_liang_liuhou_events(store: EventStore) -> list[int]:
    """将张良主线事件写入 EventStore，已存在的同名事件会跳过。"""
    existing_keys = {
        (row["time_year"], row["event"], row["location_note"])
        for row in store.search_events(person_contains="张良", limit=1000, order="time")
    }
    created_ids: list[int] = []
    for event in ZHANG_LIANG_LIUHOU_EVENTS:
        key = (int(event["time"]), event["event"], event["location_note"])
        if key in existing_keys:
            continue
        created_ids.append(store.create_event(**event))
        existing_keys.add(key)
    return created_ids


__all__ = [
    "SEED_MARKER",
    "SOURCE_URL",
    "ZHANG_LIANG_LIUHOU_EVENTS",
    "seed_zhang_liang_liuhou_events",
]
